services:
  vnc:
    container_name: vnc
    image: igzhang/vnc_brower:firefox
    ports:
      - "5905:5905"
      - "6080:6080"
    volumes:
      - ./user_data:/root/.mozilla
    environment:
      TZ: Asia/Shanghai
      ALL_PROXY: http://127.0.0.1:7890
      PASSWD: 123456
